### ISSUE TITLE
Error when using qt-release command

### ISSUE THREAD

**Issue by julian-poidevin** [strahlex/Qt-Deployment-Scripts#4]
When running command 
```Shell
$ qt-release 
```
The following message is prompted
```Shell
Traceback (most recent call last):
  File "/usr/bin/qt-release", line 7, in <module>
    import github3
ImportError: No module named github3
```

Is it possible to install missing modules during `make install` command ?

**Comment by julian-poidevin** [comment]
Had to run this command to get this working :
```
sudo python -m pip install github3.py
```

**Comment by julian-poidevin** [comment]
In fact, to get the code working, `github3.py` should be installed from develop source of the repository. Should precise this in README.md file.
I didn't understand this at first.

**Comment by machinekoder** [comment]
To be honest, I have not used the `qt-release` tool in a while because I moved to BinTray. I'm glad to hear that it works for you with the develop library.
